spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@yourdomain.com
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/chapelchat
    username: chapel
    password: chapel
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
