spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@yourdomain.com
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/chapelchat
    username: chapel
    password: chapel
    hikari:
      maximum-pool-size: 5
  liquibase:
    contexts:
      - dev
      - seed
  jpa:
    hibernate:
      ddl-auto: validate   # or none; Liquibase owns schema
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  h2:
    console:
      enabled: false
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.boot.autoconfigure.orm.jpa: DEBUG
    org.hibernate: INFO