spring:
    application:
        name: ChapelChat
    profiles:
        active: local
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml
     
openai:
    api:
        key: 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
        model: ${OPENAI_MODEL:gpt-4o}
        temperature: ${OPENAI_TEMPERATURE:0.7}
        base-url: https://api.openai.com/v1
