version: "3.9"
services:
  db:
    image: postgres:16
    container_name: chapelchat-db
    environment:
      POSTGRES_DB: chapelchat
      POSTGRES_USER: chapel
      POSTGRES_PASSWORD: chapel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chapel -d chapelchat"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata:
