package com.erikmikac.ChapelChat.model;

import lombok.Data;

/**
 * Represents a response from the "ask" endpoint.
 * It contains the generated response message.
 */
@Data
public class AskResponse {
    /** The response message generated by the service. */
    private String response;

    public AskResponse(final String response) {
        this.response = response;
    }
}
